apiVersion: v1
kind: Service

metadata:
  name: hello-world-service

spec:
  type: LoadBalancer

  selector:
    app: hello-world

  ports:
    - protocol: TCP
      port: 32777
      targetPort: 32777